spring:
  application:
    name: authentication-service
  config:
    import: "optional:configserver:http://localhost:8887"
  cloud:
    config:
      fail-fast: true
  datasource:
    url: jdbc:postgresql://localhost:5432/auth_db # Замените на ваши данные
    username: your_db_user
    password: your_db_password
    driver-class-name: org.postgresql.Driver

server:
  port: 8000